#' Sequentially Compare Multiple Lists of Tables
#'
#' This function sequentially compares multiple named lists of data frames. It is designed
#' to compare lists in a stepwise manner (e.g., A to B, B to C, etc.), storing the results
#' of each comparison.
#'
#' @param list_of_tables A list of named lists of data frames. Each named list should have identical names 
#' across all entries to ensure accurate comparisons.
#' @return A named list where each entry corresponds to the comparison results of a pair of lists.
#' Each comparison result is a named list of data frames, as generated by `compare_named_tables`.
#' @export
#' @examples
#' # Example usage:
#' list_of_tables <- list(A = tables_A, B = tables_B, C = tables_C)
#' all_comparisons <- compare_multiple_tables(list_of_tables)
compare_multiple_tables <- function(list_of_tables) {
  # Check if the input is a list of named lists
  if (!is.list(list_of_tables) || length(list_of_tables) < 2) {
    stop("The input must be a list containing at least two named lists of data frames.")
  }
  
  # Initialize an empty list to store all comparison results
  all_comparisons <- list()
  
  # Get sample names from list keys
  sample_names <- names(list_of_tables)

  # Sequentially compare each pair of tables
  for (i in 1:(length(list_of_tables) - 1)) {
    name_A <- sample_names[i]
    name_B <- sample_names[i + 1]

    cat("Comparing:", name_A, "to", name_B, "\n")

    # Extract the current and next lists to compare
    list_A <- list_of_tables[[i]]
    list_B <- list_of_tables[[i + 1]]

    # Perform the comparison with actual sample names as suffixes
    comparison_results <- compare_named_tables(
      list_A, list_B,
      name_A = paste0(name_A, "/output/index"),
      name_B = paste0(name_B, "/output/index")
    )

    # Store the comparison results with a meaningful name
    comparison_name <- paste0("Comparison_", name_A, "_to_", name_B)
    all_comparisons[[comparison_name]] <- comparison_results
  }
  
  return(all_comparisons)
}